#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."


echo "Copying component"
mkdir -p "${PWD}/config/custom_components/bing_wallpaper/"
cp -r "${PWD}"/custom_components/bing_wallpaper/* \
    "${PWD}/config/custom_components/bing_wallpaper/";
